/* Copyright 2017-2021 CNRS-AIST JRL and CNRS-UM LIRMM */

#pragma once

/** This file is generated by CMake, edit @PROJECT_SOURCE_DIR@/include/tvm/supported_solvers.in.h if needed */

/** For every supported solvers in TVM:
 * - define a related macro (e.g. TVM_USE_LSSOL)
 * - includes the related solver
 *
 * Use defaultLeastSquareSolver if you do not care to choose a particular solver
 */

@TVM_USE_LSSOL@
#ifdef TVM_USE_LSSOL
#  include <tvm/solver/LSSOLLeastSquareSolver.h>
#endif

@TVM_USE_QLD@
#ifdef TVM_USE_QLD
#  include <tvm/solver/QLDLeastSquareSolver.h>
#endif

@TVM_USE_QUADPROG@
#ifdef TVM_USE_QUADPROG
#  include <tvm/solver/QuadprogLeastSquareSolver.h>
#endif

#include <tvm/solver/defaultLeastSquareSolver.h>
