TVM: tvm::graph::internal Namespace Reference
tvm::graph::internal Namespace Reference
Classes
class AbstractNode
An abstract node is the structure stored in the call graph to hide away the actual type of the node.
class Inputs
Inputs store a list of Outputs and the required output signals.
class Log
A data structure, used by Logger to log the inputs, outputs, updates and dependencies that are declared at runtime.
class Logger
Functions
template<typename T , typename EnumT >
constexpr bool is_valid_update (EnumT v)
Check if a value of EnumT is a valid update for Node type T.
template<typename T , typename EnumT , typename ... Args>
constexpr bool is_valid_update (EnumT v, Args ... args)
Check if all values of a given set are valid updates for Updates type T.
template<typename ObjType , typename MemberType , typename... Args>
bool lexLess (const ObjType &l, const ObjType &r, MemberType ObjType::*member, Args &&... args)
lexicographic comparison of two objects given an ordered list of the members to compare.
template<typename ObjType , typename MemberType , typename... Args>
bool eq (const ObjType &l, const ObjType &r, MemberType ObjType::*member, Args &&... args)
Equality comparison of two objects given an ordered list of the members to compare.
template<typename ObjType , typename MemberType >
bool lexLess (const ObjType &l, const ObjType &r, MemberType ObjType::*member)
End of recursion.
template<typename ObjType , typename MemberType >
bool eq (const ObjType &l, const ObjType &r, MemberType ObjType::*member)
End of recursion.
template<typename T >
std::uintptr_t getPointerValue (void(T::*ptfm)())
Function Documentation
eq() [1/2]
template<typename ObjType , typename MemberType , typename... Args> bool tvm::graph::internal::eq (const ObjType & l, const ObjType & r, MemberType ObjType::* member, Args &&... args)
Equality comparison of two objects given an ordered list of the members to compare.
Referenced by tvm::graph::internal::Log::EnumValue::operator==(), tvm::graph::internal::Log::Pointer::operator==(), tvm::graph::internal::Log::Update::operator==(), tvm::graph::internal::Log::Output::operator==(), tvm::graph::internal::Log::Input::operator==(), tvm::graph::internal::Log::InputDependency::operator==(), tvm::graph::internal::Log::OutputDependency::operator==(), tvm::graph::internal::Log::InternalDependency::operator==(), and tvm::graph::internal::Log::DirectDependency::operator==().
eq() [2/2]
template<typename ObjType , typename MemberType > bool tvm::graph::internal::eq (const ObjType & l, const ObjType & r, MemberType ObjType::* member)
End of recursion.
getPointerValue()
template<typename T > std::uintptr_t tvm::graph::internal::getPointerValue (void(T::*)() ptfm)
is_valid_update() [1/2]
template<typename T , typename EnumT > constexpr bool tvm::graph::internal::is_valid_update (EnumT v)
Check if a value of EnumT is a valid update for Node type T.
is_valid_update() [2/2]
template<typename T , typename EnumT , typename ... Args> constexpr bool tvm::graph::internal::is_valid_update (EnumT v, Args ... args)
Check if all values of a given set are valid updates for Updates type T.
lexLess() [1/2]
template<typename ObjType , typename MemberType , typename... Args> bool tvm::graph::internal::lexLess (const ObjType & l, const ObjType & r, MemberType ObjType::* member, Args &&... args)
lexicographic comparison of two objects given an ordered list of the members to compare.
Referenced by tvm::graph::internal::Log::EnumValue::operator<(), tvm::graph::internal::Log::Pointer::operator<(), tvm::graph::internal::Log::Update::operator<(), tvm::graph::internal::Log::Output::operator<(), tvm::graph::internal::Log::Input::operator<(), tvm::graph::internal::Log::InputDependency::operator<(), tvm::graph::internal::Log::OutputDependency::operator<(), tvm::graph::internal::Log::InternalDependency::operator<(), and tvm::graph::internal::Log::DirectDependency::operator<().
lexLess() [2/2]
template<typename ObjType , typename MemberType > bool tvm::graph::internal::lexLess (const ObjType & l, const ObjType & r, MemberType ObjType::* member)
End of recursion.