TVM: ProtoTask.h File Reference
ProtoTask.h File Reference
#include <tvm/api.h>
#include <tvm/utils/AffineExpr.h>
#include <tvm/utils/internal/ProtoTaskDetails.h>
Classes
class tvm::utils::ProtoTaskCommon< T, FunT >
class tvm::utils::ProtoTaskCommon< T, FunT >
class tvm::utils::ProtoTaskCommon< constraint::Type::DOUBLE_SIDED, FunT >
Namespaces
tvm
Copyright 2017-2020 CNRS-AIST JRL and CNRS-UM LIRMM.
tvm::utils
Copyright 2017-2020 CNRS-AIST JRL and CNRS-UM LIRMM.
Macros
#define TVM_ID(x) std::make_shared<tvm::function::IdentityFunction>(x)
#define TVM_LIN(x) std::make_shared<tvm::function::BasicLinearFunction>(x)
Typedefs
template<constraint::Type T>
using tvm::utils::ProtoTask = ProtoTaskCommon< T, FunctionPtr >
A utility class to represent the "constraint" part of a Task, for general functions.
template<constraint::Type T>
using tvm::utils::LinearProtoTask = ProtoTaskCommon< T, LinearFunctionPtr >
A utility class to represent the "constraint" part of a Task, specialized for linear functions.
template<typename T , typename IfNotLinearFunction , typename IfLinearFunction >
using tvm::utils::ProtoChoice = typename std::enable_if< std::is_base_of< tvm::function::abstract::Function, T >::value, typename std::conditional< std::is_base_of< tvm::function::abstract::LinearFunction, T >::value, IfLinearFunction, IfNotLinearFunction >::type >::type
A helper alias that is IfNotLinearFunction if T is a tvm::abstract::Function, but not a tvm::abstract::LinearFunction, IfLinearFunction if it is a tvm::abstract::LinearFunction, and nothing (discarded by SFINAE) otherwise.
using tvm::utils::ProtoTaskEQ = ProtoTask< constraint::Type::EQUAL >
Equality ProtoTask f = rhs.
using tvm::utils::LinearProtoTaskEQ = LinearProtoTask< constraint::Type::EQUAL >
template<typename T >
using tvm::utils::ProtoTaskEQRet = ProtoChoice< T, tvm::utils::ProtoTaskEQ, tvm::utils::LinearProtoTaskEQ >
using tvm::utils::ProtoTaskLT = ProtoTask< constraint::Type::LOWER_THAN >
Inequality ProtoTask f <= rhs.
using tvm::utils::LinearProtoTaskLT = LinearProtoTask< constraint::Type::LOWER_THAN >
template<typename T >
using tvm::utils::ProtoTaskLTRet = ProtoChoice< T, tvm::utils::ProtoTaskLT, tvm::utils::LinearProtoTaskLT >
using tvm::utils::ProtoTaskGT = ProtoTask< constraint::Type::GREATER_THAN >
Inequality ProtoTask f >= rhs.
using tvm::utils::LinearProtoTaskGT = LinearProtoTask< constraint::Type::GREATER_THAN >
template<typename T >
using tvm::utils::ProtoTaskGTRet = ProtoChoice< T, tvm::utils::ProtoTaskGT, tvm::utils::LinearProtoTaskGT >
using tvm::utils::ProtoTaskDS = ProtoTask< constraint::Type::DOUBLE_SIDED >
Double sided inequality ProtoTask l <= f <= u.
using tvm::utils::LinearProtoTaskDS = LinearProtoTask< constraint::Type::DOUBLE_SIDED >
template<typename T >
using tvm::utils::ProtoTaskDSRet = ProtoChoice< T, tvm::utils::ProtoTaskDS, tvm::utils::LinearProtoTaskDS >
Functions
template<typename F >
tvm::utils::ProtoTaskEQRet< F > operator== (std::shared_ptr< F > f, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
template<typename F >
tvm::utils::ProtoTaskEQRet< F > operator== (const tvm::utils::internal::RHS &rhs, std::shared_ptr< F > f)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
template<typename F >
tvm::utils::ProtoTaskGTRet< F > operator>= (std::shared_ptr< F > f, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
template<typename F >
tvm::utils::ProtoTaskLTRet< F > operator>= (const tvm::utils::internal::RHS &rhs, std::shared_ptr< F > f)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
template<typename F >
tvm::utils::ProtoTaskLTRet< F > operator<= (std::shared_ptr< F > f, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
template<typename F >
tvm::utils::ProtoTaskGTRet< F > operator<= (const tvm::utils::internal::RHS &rhs, std::shared_ptr< F > f)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
tvm::utils::ProtoTaskDS operator>= (const tvm::utils::ProtoTaskLT &ptl, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
tvm::utils::ProtoTaskDS operator<= (const tvm::utils::ProtoTaskGT &ptg, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
tvm::utils::LinearProtoTaskEQ operator== (tvm::VariablePtr x, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::internal::RHS &rhs, tvm::VariablePtr x)
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
tvm::utils::LinearProtoTaskGT operator>= (tvm::VariablePtr x, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
tvm::utils::LinearProtoTaskLT operator>= (const tvm::utils::internal::RHS &rhs, tvm::VariablePtr x)
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
tvm::utils::LinearProtoTaskLT operator<= (tvm::VariablePtr x, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
tvm::utils::LinearProtoTaskGT operator<= (const tvm::utils::internal::RHS &rhs, tvm::VariablePtr x)
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
template<typename Derived >
tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::LinearExpr< Derived > &lin, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename Derived >
tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::internal::RHS &rhs, const tvm::utils::LinearExpr< Derived > &lin)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename Derived >
tvm::utils::LinearProtoTaskGT operator>= (const tvm::utils::LinearExpr< Derived > &lin, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename Derived >
tvm::utils::LinearProtoTaskLT operator>= (const tvm::utils::internal::RHS &rhs, const tvm::utils::LinearExpr< Derived > &lin)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename Derived >
tvm::utils::LinearProtoTaskLT operator<= (const tvm::utils::LinearExpr< Derived > &lin, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename Derived >
tvm::utils::LinearProtoTaskGT operator<= (const tvm::utils::internal::RHS &rhs, const tvm::utils::LinearExpr< Derived > &lin)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename CstDerived , typename... Derived>
tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::AffineExpr< CstDerived, Derived... > &aff, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename CstDerived , typename... Derived>
tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::internal::RHS &rhs, const tvm::utils::AffineExpr< CstDerived, Derived... > &aff)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename CstDerived , typename... Derived>
tvm::utils::LinearProtoTaskGT operator>= (const tvm::utils::AffineExpr< CstDerived, Derived... > &aff, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename CstDerived , typename... Derived>
tvm::utils::LinearProtoTaskLT operator>= (const tvm::utils::internal::RHS &rhs, const tvm::utils::AffineExpr< CstDerived, Derived... > &aff)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename CstDerived , typename... Derived>
tvm::utils::LinearProtoTaskLT operator<= (const tvm::utils::AffineExpr< CstDerived, Derived... > &aff, const tvm::utils::internal::RHS &rhs)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
template<typename CstDerived , typename... Derived>
tvm::utils::LinearProtoTaskGT operator<= (const tvm::utils::internal::RHS &rhs, const tvm::utils::AffineExpr< CstDerived, Derived... > &aff)
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Macro Definition Documentation
TVM_ID
#define TVM_ID (x) std::make_shared<tvm::function::IdentityFunction>(x)
Referenced by operator<=(), operator==(), and operator>=().
TVM_LIN
#define TVM_LIN (x) std::make_shared<tvm::function::BasicLinearFunction>(x)
Referenced by operator<=(), operator==(), and operator>=().
Function Documentation
operator<=() [1/9]
template<typename F > tvm::utils::ProtoTaskLTRet<F> operator<= (std::shared_ptr< F > f, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
Referenced by operator<=().
operator<=() [2/9]
template<typename F > tvm::utils::ProtoTaskGTRet<F> operator<= (const tvm::utils::internal::RHS & rhs, std::shared_ptr< F > f) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
operator<=() [3/9]
tvm::utils::LinearProtoTaskDS operator<= (const tvm::utils::ProtoTaskGT & ptg, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References tvm::utils::ProtoTaskCommon< T, FunT >::f_, operator<=(), operator>=(), and tvm::utils::ProtoTaskCommon< T, FunT >::rhs_.
operator<=() [4/9]
tvm::utils::LinearProtoTaskLT operator<= (tvm::VariablePtr x, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
Parameters
x the variable used in the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References TVM_ID.
operator<=() [5/9]
tvm::utils::LinearProtoTaskGT operator<= (const tvm::utils::internal::RHS & rhs, tvm::VariablePtr x) inline
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
Parameters
x the variable used in the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References TVM_ID.
operator<=() [6/9]
template<typename Derived > tvm::utils::LinearProtoTaskLT operator<= (const tvm::utils::LinearExpr< Derived > & lin, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator<=() [7/9]
template<typename Derived > tvm::utils::LinearProtoTaskGT operator<= (const tvm::utils::internal::RHS & rhs, const tvm::utils::LinearExpr< Derived > & lin) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator<=() [8/9]
template<typename CstDerived , typename... Derived> tvm::utils::LinearProtoTaskLT operator<= (const tvm::utils::AffineExpr< CstDerived, Derived... > & aff, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator<=() [9/9]
template<typename CstDerived , typename... Derived> tvm::utils::LinearProtoTaskGT operator<= (const tvm::utils::internal::RHS & rhs, const tvm::utils::AffineExpr< CstDerived, Derived... > & aff) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator==() [1/8]
template<typename F > tvm::utils::ProtoTaskEQRet<F> operator== (std::shared_ptr< F > f, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
operator==() [2/8]
template<typename F > tvm::utils::ProtoTaskEQRet<F> operator== (const tvm::utils::internal::RHS & rhs, std::shared_ptr< F > f) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
operator==() [3/8]
tvm::utils::LinearProtoTaskEQ operator== (tvm::VariablePtr x, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
Parameters
x the variable used in the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References TVM_ID.
operator==() [4/8]
tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::internal::RHS & rhs, tvm::VariablePtr x) inline
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
Parameters
x the variable used in the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References TVM_ID.
operator==() [5/8]
template<typename Derived > tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::LinearExpr< Derived > & lin, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator==() [6/8]
template<typename Derived > tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::internal::RHS & rhs, const tvm::utils::LinearExpr< Derived > & lin) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator==() [7/8]
template<typename CstDerived , typename... Derived> tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::AffineExpr< CstDerived, Derived... > & aff, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator==() [8/8]
template<typename CstDerived , typename... Derived> tvm::utils::LinearProtoTaskEQ operator== (const tvm::utils::internal::RHS & rhs, const tvm::utils::AffineExpr< CstDerived, Derived... > & aff) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator>=() [1/9]
template<typename F > tvm::utils::ProtoTaskGTRet<F> operator>= (std::shared_ptr< F > f, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
Referenced by operator<=().
operator>=() [2/9]
template<typename F > tvm::utils::ProtoTaskLTRet<F> operator>= (const tvm::utils::internal::RHS & rhs, std::shared_ptr< F > f) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
operator>=() [3/9]
tvm::utils::LinearProtoTaskDS operator>= (const tvm::utils::ProtoTaskLT & ptl, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a ProtoTask or LinearProtoTask f op rhs (or l <= f <= u)
Parameters
f the function to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References tvm::utils::ProtoTaskCommon< T, FunT >::f_, and tvm::utils::ProtoTaskCommon< T, FunT >::rhs_.
operator>=() [4/9]
tvm::utils::LinearProtoTaskGT operator>= (tvm::VariablePtr x, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
Parameters
x the variable used in the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References TVM_ID.
operator>=() [5/9]
tvm::utils::LinearProtoTaskLT operator>= (const tvm::utils::internal::RHS & rhs, tvm::VariablePtr x) inline
Convenience operators to form a LinearProtoTask x op rhs (or l <= x <= u)
Parameters
x the variable used in the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you need to explicitly write a double (e.g 0., not 0), otherwise the compiler won't be able to decide which overload to pick between this and shared_ptr operator.
References TVM_ID.
operator>=() [6/9]
template<typename Derived > tvm::utils::LinearProtoTaskGT operator>= (const tvm::utils::LinearExpr< Derived > & lin, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator>=() [7/9]
template<typename Derived > tvm::utils::LinearProtoTaskLT operator>= (const tvm::utils::internal::RHS & rhs, const tvm::utils::LinearExpr< Derived > & lin) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator>=() [8/9]
template<typename CstDerived , typename... Derived> tvm::utils::LinearProtoTaskGT operator>= (const tvm::utils::AffineExpr< CstDerived, Derived... > & aff, const tvm::utils::internal::RHS & rhs) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.
operator>=() [9/9]
template<typename CstDerived , typename... Derived> tvm::utils::LinearProtoTaskLT operator>= (const tvm::utils::internal::RHS & rhs, const tvm::utils::AffineExpr< CstDerived, Derived... > & aff) inline
Convenience operators to form a LinearProtoTask expr op rhs (or l <= expr <= u) where expr is a linear expression of the form matrixExpr * VariablePtr or an affine expression as a sum of linear expressions and vectorExpr.
Parameters
lin the linear expression to form the task
aff the affine expression to form the task
rhs a double or a Eigen::Vector with the same size as the function. Note that for a double you don't need to explicitly write a double (e.g 0.) to the contrary of the operators working with shared_ptr on Function.
References TVM_LIN.