TVM: tvm::utils Namespace Reference
tvm::utils Namespace Reference
Namespaces
internal
Classes
class AffineExpr
A class representing an affine expression A1 * x1 + A2 *x2 + ...
class CheckOptions
A small structure to specify options for the checks in CheckGroup.
class LinearExpr
A class representing an expression A * x with A a matrix expression and x a variable.
class ProtoTaskCommon
class ProtoTaskCommon< constraint::Type::DOUBLE_SIDED, FunT >
class UpdatelessFunction
This class wraps a function to mask the update mechanism to the user, by providing methods as value and jacobian that can be called directly with the values of the variables.
Typedefs
template<constraint::Type T>
using ProtoTask = ProtoTaskCommon< T, FunctionPtr >
A utiliy class to represent the "constraint" part of a Task, for general functions.
template<constraint::Type T>
using LinearProtoTask = ProtoTaskCommon< T, LinearFunctionPtr >
A utiliy class to represent the "constraint" part of a Task, specialized for linear functions.
template<typename T , typename IfNotLinearFunction , typename IfLinearFunction >
using ProtoChoice = typename std::enable_if< std::is_base_of< tvm::function::abstract::Function, T >::value, typename std::conditional< std::is_base_of< tvm::function::abstract::LinearFunction, T >::value, IfLinearFunction, IfNotLinearFunction >::type >::type
A helper alias that is IfNotLinearFunction if T is a tvm::abstract::Function, but not a tvm::abstract::LinearFunction, IfLinearFunction if it is a tvm::abstract::LinearFunction, and nothing (discarded by SFINAE) otherwise.
using ProtoTaskEQ = ProtoTask< constraint::Type::EQUAL >
Equality ProtoTask f = rhs.
using LinearProtoTaskEQ = LinearProtoTask< constraint::Type::EQUAL >
template<typename T >
using ProtoTaskEQRet = ProtoChoice< T, tvm::utils::ProtoTaskEQ, tvm::utils::LinearProtoTaskEQ >
using ProtoTaskLT = ProtoTask< constraint::Type::LOWER_THAN >
Inequality ProtoTask f <= rhs.
using LinearProtoTaskLT = LinearProtoTask< constraint::Type::LOWER_THAN >
template<typename T >
using ProtoTaskLTRet = ProtoChoice< T, tvm::utils::ProtoTaskLT, tvm::utils::LinearProtoTaskLT >
using ProtoTaskGT = ProtoTask< constraint::Type::GREATER_THAN >
Inequality ProtoTask f >= rhs.
using LinearProtoTaskGT = LinearProtoTask< constraint::Type::GREATER_THAN >
template<typename T >
using ProtoTaskGTRet = ProtoChoice< T, tvm::utils::ProtoTaskGT, tvm::utils::LinearProtoTaskGT >
using ProtoTaskDS = ProtoTask< constraint::Type::DOUBLE_SIDED >
Double sided inequality ProtoTask l <= f <= u.
using LinearProtoTaskDS = LinearProtoTask< constraint::Type::DOUBLE_SIDED >
template<typename T >
using ProtoTaskDSRet = ProtoChoice< T, tvm::utils::ProtoTaskDS, tvm::utils::LinearProtoTaskDS >
Functions
template<unsigned int N>
constexpr unsigned int count_va_args (const char(&s)[N], unsigned int i=0, unsigned int ret=0)
Constexpr function to compute the size of VA_ARGS in a macro.
template<typename CstDerived , typename... Derived>
AffineExpr< CstDerived, Derived... > make_AffineExpr (const CstDerived &constant, const std::tuple< LinearExpr< Derived >... > &linear)
Helper function to create a AffineExpr and infer automatically the template arguments.
bool TVM_DLLAPI checkJacobian (FunctionPtr f, CheckOptions opt=CheckOptions())
Check the jacobian matrices of function f by forward finite differences.
template<typename Object , typename... Args>
std::unique_ptr< graph::CallGraph > generateUpdateGraph (std::shared_ptr< Object > obj, Args &&... args)
Generate the graph of updates for a list of objects and their specified outputs.
template<typename Derived >
auto operator- (const tvm::utils::LinearExpr< Derived > &lin)
Lin = -Lin.
template<typename CstDerived , typename... Derived>
auto operator- (const tvm::utils::AffineExpr< CstDerived, Derived... > &aff)
Aff = -Aff.
template<typename MultDerived , typename CstDerived , typename... Derived>
auto operator* (const MultDerived &m, const tvm::utils::AffineExpr< CstDerived, Derived... > &aff)
Aff = m*Aff, where m is any type accepted by Eigen for pre-multiplication (in particular scalar or matrix expression).
template<typename Derived , typename CstDerived >
tvm::utils::AffineExpr< CstDerived, Derived > operator+ (const tvm::utils::LinearExpr< Derived > &lin, const Eigen::MatrixBase< CstDerived > &cst)
Aff = Lin + b.
template<typename Derived , typename CstDerived >
tvm::utils::AffineExpr< CstDerived, Derived > operator+ (const Eigen::MatrixBase< CstDerived > &cst, const tvm::utils::LinearExpr< Derived > &lin)
Aff = b + Lin.
template<typename LhsDerived , typename RhsDerived >
tvm::utils::AffineExpr< tvm::utils::internal::NoConstant, LhsDerived, RhsDerived > operator+ (const tvm::utils::LinearExpr< LhsDerived > &lhs, const tvm::utils::LinearExpr< RhsDerived > &rhs)
Aff = Lin + Lin.
template<typename RhsDerived , typename CstDerived , typename ... LhsDerived>
tvm::utils::AffineExpr< CstDerived, LhsDerived..., RhsDerived > operator+ (const tvm::utils::AffineExpr< CstDerived, LhsDerived... > &lhs, const tvm::utils::LinearExpr< RhsDerived > &rhs)
Aff = Aff + Lin.
template<typename LhsDerived , typename CstDerived , typename ... RhsDerived>
tvm::utils::AffineExpr< CstDerived, LhsDerived, RhsDerived... > operator+ (const tvm::utils::LinearExpr< LhsDerived > &lhs, const tvm::utils::AffineExpr< CstDerived, RhsDerived... > &rhs)
Aff = Lin + Aff.
template<typename RhsDerived , typename CstDerived , typename ... LhsDerived>
tvm::utils::AffineExpr< tvm::utils::internal::AddConstantsRetType< CstDerived, RhsDerived >, LhsDerived... > operator+ (const tvm::utils::AffineExpr< CstDerived, LhsDerived... > &lhs, const Eigen::MatrixBase< RhsDerived > &rhs)
Aff = Aff + b.
template<typename LhsDerived , typename CstDerived , typename ... RhsDerived>
tvm::utils::AffineExpr< tvm::utils::internal::AddConstantsRetType< LhsDerived, CstDerived >, RhsDerived... > operator+ (const Eigen::MatrixBase< LhsDerived > &lhs, const tvm::utils::AffineExpr< CstDerived, RhsDerived... > &rhs)
Aff = b + Aff.
template<typename LCstDerived , typename RCstDerived , typename ... LhsDerived, typename ... RhsDerived>
tvm::utils::AffineExpr< tvm::utils::internal::AddConstantsRetType< LCstDerived, RCstDerived >, LhsDerived..., RhsDerived... > operator+ (const tvm::utils::AffineExpr< LCstDerived, LhsDerived... > &lhs, const tvm::utils::AffineExpr< RCstDerived, RhsDerived... > &rhs)
Aff = Aff + Aff.
template<typename MultType , typename Derived >
auto operator* (const MultType &m, const tvm::utils::LinearExpr< Derived > &lin)
Lin = m * Lin.
template<typename Derived , typename SubType , typename tvm::internal::enable_for_templated_t< SubType, Eigen::MatrixBase, tvm::utils::LinearExpr, tvm::utils::AffineExpr > = 0>
auto operator- (const tvm::utils::LinearExpr< Derived > &lin, const SubType &rhs)
Aff = Lin - a.
template<typename CstDerived , typename SubType , typename... Derived, typename tvm::internal::enable_for_templated_t< SubType, Eigen::MatrixBase, tvm::utils::LinearExpr, tvm::utils::AffineExpr > = 0>
auto operator- (const tvm::utils::AffineExpr< CstDerived, Derived... > &aff, const SubType &rhs)
Aff = Aff - a.
TVM_DLLAPI void transform (sch::S_Object &obj, const sva::PTransformd &t)
Set obj pose to t.
TVM_DLLAPI std::unique_ptr< sch::S_Polyhedron > Polyhedron (const std::string &filename)
Loads an sch::S_Polyhedron object using filename.
TVM_DLLAPI double distance (sch::CD_Pair &pair, Eigen::Vector3d &p1, Eigen::Vector3d &p2)
Compute distance between two objects.
Typedef Documentation
LinearProtoTask
template<constraint::Type T> using tvm::utils::LinearProtoTask = typedef ProtoTaskCommon<T, LinearFunctionPtr>
A utiliy class to represent the "constraint" part of a Task, specialized for linear functions.
LinearProtoTaskDS
using tvm::utils::LinearProtoTaskDS = typedef LinearProtoTask<constraint::Type::DOUBLE_SIDED>
LinearProtoTaskEQ
using tvm::utils::LinearProtoTaskEQ = typedef LinearProtoTask<constraint::Type::EQUAL>
LinearProtoTaskGT
using tvm::utils::LinearProtoTaskGT = typedef LinearProtoTask<constraint::Type::GREATER_THAN>
LinearProtoTaskLT
using tvm::utils::LinearProtoTaskLT = typedef LinearProtoTask<constraint::Type::LOWER_THAN>
ProtoChoice
template<typename T , typename IfNotLinearFunction , typename IfLinearFunction > using tvm::utils::ProtoChoice = typedef typename std::enable_if< std::is_base_of<tvm::function::abstract::Function, T>::value, typename std::conditional< std::is_base_of<tvm::function::abstract::LinearFunction, T>::value, IfLinearFunction, IfNotLinearFunction >::type >::type
A helper alias that is IfNotLinearFunction if T is a tvm::abstract::Function, but not a tvm::abstract::LinearFunction, IfLinearFunction if it is a tvm::abstract::LinearFunction, and nothing (discarded by SFINAE) otherwise.
ProtoTask
template<constraint::Type T> using tvm::utils::ProtoTask = typedef ProtoTaskCommon<T, FunctionPtr>
A utiliy class to represent the "constraint" part of a Task, for general functions.
ProtoTaskDS
using tvm::utils::ProtoTaskDS = typedef ProtoTask<constraint::Type::DOUBLE_SIDED>
Double sided inequality ProtoTask l <= f <= u.
ProtoTaskDSRet
template<typename T > using tvm::utils::ProtoTaskDSRet = typedef ProtoChoice<T, tvm::utils::ProtoTaskDS, tvm::utils::LinearProtoTaskDS>
ProtoTaskEQ
using tvm::utils::ProtoTaskEQ = typedef ProtoTask<constraint::Type::EQUAL>
Equality ProtoTask f = rhs.
ProtoTaskEQRet
template<typename T > using tvm::utils::ProtoTaskEQRet = typedef ProtoChoice<T, tvm::utils::ProtoTaskEQ, tvm::utils::LinearProtoTaskEQ>
ProtoTaskGT
using tvm::utils::ProtoTaskGT = typedef ProtoTask<constraint::Type::GREATER_THAN>
Inequality ProtoTask f >= rhs.
ProtoTaskGTRet
template<typename T > using tvm::utils::ProtoTaskGTRet = typedef ProtoChoice<T, tvm::utils::ProtoTaskGT, tvm::utils::LinearProtoTaskGT>
ProtoTaskLT
using tvm::utils::ProtoTaskLT = typedef ProtoTask<constraint::Type::LOWER_THAN>
Inequality ProtoTask f <= rhs.
ProtoTaskLTRet
template<typename T > using tvm::utils::ProtoTaskLTRet = typedef ProtoChoice<T, tvm::utils::ProtoTaskLT, tvm::utils::LinearProtoTaskLT>
Function Documentation
count_va_args()
template<unsigned int N> constexpr unsigned int tvm::utils::count_va_args (const char(&) s[N], unsigned int i = 0, unsigned int ret = 0)
Constexpr function to compute the size of VA_ARGS in a macro.
Does not work if VA_ARGS arguments contains a string with an embedded ',' character. This should not happen in the context we use this function.
Inspired by https://stackoverflow.com/a/35868609
Counts the number of ',' in the stringified version of VA_ARGS
distance()
TVM_DLLAPI double tvm::utils::distance (sch::CD_Pair & pair, Eigen::Vector3d & p1, Eigen::Vector3d & p2)
Compute distance between two objects.
Parameters
pair pair of SCH objects
p1 will be the closest point in the first object
p2 will be the closes point in the second object
Returns
The squared distance between the two objects, returns a negative distance in case of inter-penetration
generateUpdateGraph()
template<typename Object , typename... Args> std::unique_ptr< graph::CallGraph > tvm::utils::generateUpdateGraph (std::shared_ptr< Object > obj, Args &&... args) inline
Generate the graph of updates for a list of objects and their specified outputs.
g = generateUpdateGraph(obj1, o1_1, ..., o1_n1, obj2, o2_1, ..., o2_n2, ..., objk, ok_1, ..., ok_nk) generates a graph g such that g.execute() ensures that outputs o1_1, ... o1_n1 for obj1, o2_1, ... o2_1 for obj2, etc. are up to date.
References tvm::utils::internal::parseSourcesAndOutputs().
make_AffineExpr()
template<typename CstDerived , typename... Derived> AffineExpr<CstDerived, Derived...> tvm::utils::make_AffineExpr (const CstDerived & constant, const std::tuple< LinearExpr< Derived >... > & linear)
Helper function to create a AffineExpr and infer automatically the template arguments.
Referenced by operator*(), and operator-().
operator*() [1/2]
template<typename MultDerived , typename CstDerived , typename... Derived> auto tvm::utils::operator* (const MultDerived & m, const tvm::utils::AffineExpr< CstDerived, Derived... > & aff) inline
Aff = m*Aff, where m is any type accepted by Eigen for pre-multiplication (in particular scalar or matrix expression).
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), tvm::utils::AffineExpr< CstDerived, Derived >::linear(), make_AffineExpr(), and tvm::utils::internal::tuplePremult().
operator*() [2/2]
template<typename MultType , typename Derived > auto tvm::utils::operator* (const MultType & m, const tvm::utils::LinearExpr< Derived > & lin) inline
Lin = m * Lin.
References tvm::utils::LinearExpr< Derived >::matrix(), and tvm::utils::LinearExpr< Derived >::variable().
operator+() [1/8]
template<typename Derived , typename CstDerived > tvm::utils::AffineExpr<CstDerived, Derived> tvm::utils::operator+ (const tvm::utils::LinearExpr< Derived > & lin, const Eigen::MatrixBase< CstDerived > & cst) inline
Aff = Lin + b.
operator+() [2/8]
template<typename Derived , typename CstDerived > tvm::utils::AffineExpr<CstDerived, Derived> tvm::utils::operator+ (const Eigen::MatrixBase< CstDerived > & cst, const tvm::utils::LinearExpr< Derived > & lin) inline
Aff = b + Lin.
operator+() [3/8]
template<typename LhsDerived , typename RhsDerived > tvm::utils::AffineExpr<tvm::utils::internal::NoConstant, LhsDerived, RhsDerived> tvm::utils::operator+ (const tvm::utils::LinearExpr< LhsDerived > & lhs, const tvm::utils::LinearExpr< RhsDerived > & rhs) inline
Aff = Lin + Lin.
operator+() [4/8]
template<typename RhsDerived , typename CstDerived , typename ... LhsDerived> tvm::utils::AffineExpr<CstDerived, LhsDerived..., RhsDerived> tvm::utils::operator+ (const tvm::utils::AffineExpr< CstDerived, LhsDerived... > & lhs, const tvm::utils::LinearExpr< RhsDerived > & rhs) inline
Aff = Aff + Lin.
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), and tvm::utils::AffineExpr< CstDerived, Derived >::linear().
operator+() [5/8]
template<typename LhsDerived , typename CstDerived , typename ... RhsDerived> tvm::utils::AffineExpr<CstDerived, LhsDerived, RhsDerived...> tvm::utils::operator+ (const tvm::utils::LinearExpr< LhsDerived > & lhs, const tvm::utils::AffineExpr< CstDerived, RhsDerived... > & rhs) inline
Aff = Lin + Aff.
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), and tvm::utils::AffineExpr< CstDerived, Derived >::linear().
operator+() [6/8]
template<typename RhsDerived , typename CstDerived , typename ... LhsDerived> tvm::utils::AffineExpr<tvm::utils::internal::AddConstantsRetType<CstDerived, RhsDerived>, LhsDerived...> tvm::utils::operator+ (const tvm::utils::AffineExpr< CstDerived, LhsDerived... > & lhs, const Eigen::MatrixBase< RhsDerived > & rhs) inline
Aff = Aff + b.
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), and tvm::utils::AffineExpr< CstDerived, Derived >::linear().
operator+() [7/8]
template<typename LhsDerived , typename CstDerived , typename ... RhsDerived> tvm::utils::AffineExpr<tvm::utils::internal::AddConstantsRetType<LhsDerived, CstDerived>, RhsDerived...> tvm::utils::operator+ (const Eigen::MatrixBase< LhsDerived > & lhs, const tvm::utils::AffineExpr< CstDerived, RhsDerived... > & rhs) inline
Aff = b + Aff.
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), and tvm::utils::AffineExpr< CstDerived, Derived >::linear().
operator+() [8/8]
template<typename LCstDerived , typename RCstDerived , typename ... LhsDerived, typename ... RhsDerived> tvm::utils::AffineExpr<tvm::utils::internal::AddConstantsRetType<LCstDerived, RCstDerived>, LhsDerived..., RhsDerived...> tvm::utils::operator+ (const tvm::utils::AffineExpr< LCstDerived, LhsDerived... > & lhs, const tvm::utils::AffineExpr< RCstDerived, RhsDerived... > & rhs) inline
Aff = Aff + Aff.
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), and tvm::utils::AffineExpr< CstDerived, Derived >::linear().
operator-() [1/4]
template<typename Derived > auto tvm::utils::operator- (const tvm::utils::LinearExpr< Derived > & lin) inline
Lin = -Lin.
References tvm::utils::LinearExpr< Derived >::matrix(), and tvm::utils::LinearExpr< Derived >::variable().
operator-() [2/4]
template<typename CstDerived , typename... Derived> auto tvm::utils::operator- (const tvm::utils::AffineExpr< CstDerived, Derived... > & aff) inline
Aff = -Aff.
References tvm::utils::AffineExpr< CstDerived, Derived >::constant(), tvm::utils::AffineExpr< CstDerived, Derived >::linear(), make_AffineExpr(), and tvm::utils::internal::tupleUnaryMinus().
operator-() [3/4]
template<typename Derived , typename SubType , typename tvm::internal::enable_for_templated_t< SubType, Eigen::MatrixBase, tvm::utils::LinearExpr, tvm::utils::AffineExpr > = 0> auto tvm::utils::operator- (const tvm::utils::LinearExpr< Derived > & lin, const SubType & rhs) inline
Aff = Lin - a.
operator-() [4/4]
template<typename CstDerived , typename SubType , typename... Derived, typename tvm::internal::enable_for_templated_t< SubType, Eigen::MatrixBase, tvm::utils::LinearExpr, tvm::utils::AffineExpr > = 0> auto tvm::utils::operator- (const tvm::utils::AffineExpr< CstDerived, Derived... > & aff, const SubType & rhs) inline
Aff = Aff - a.
Polyhedron()
TVM_DLLAPI std::unique_ptr<sch::S_Polyhedron> tvm::utils::Polyhedron (const std::string & filename)
Loads an sch::S_Polyhedron object using filename.
transform()
TVM_DLLAPI void tvm::utils::transform (sch::S_Object & obj, const sva::PTransformd & t)
Set obj pose to t.