TVM: tvm::utils::internal Namespace Reference
tvm::utils::internal Namespace Reference
Classes
class BufferedMatrix
This class provides a matrix with resizable buffer, so that allocations are made only if there is not enough space.
class IdComparator
class NoConstant
A dummy class to represent the absence of constant part in an affine expression.
struct RefSelector
Shortcut to an internal Eigen type to store expressions or matrices.
struct RefSelector< NoConstant >
class RHS
A union-like class, that can represent nothing, a double or a vector.
Typedefs
using IdentityType = decltype(Eigen::MatrixXd::Identity())
Type of Eigen::MatrixXd::Identity()
using MultIdentityType = decltype(2. *Eigen::MatrixXd::Identity())
Type of double*Eigen::MatrixXd::Identity()
using MinusIdentityType = decltype(-Eigen::MatrixXd::Identity())
Type of -Eigen::MatrixXd::Identity()
template<typename Derived >
using RefSelector_t = typename RefSelector< Derived >::type
template<typename LhsType , typename RhsType >
using AddConstantsRetType = std::remove_const_t< std::remove_reference_t< decltype(std::declval< LhsType >()+std::declval< RhsType >())> >
Result type for the addition of two constant parts, existing or not.
template<typename KeyWithId , typename Value , typename Allocator = std::allocator< std::pair<const KeyWithId, Value> >>
using map = std::map< KeyWithId, Value, IdComparator< KeyWithId >, Allocator >
Enumerations
enum RHSType {
RHSType::Zero,
RHSType::Double,
RHSType::Vector
}
Describe the type of a right-hand-side argument.
Functions
template<typename RhsType >
const RhsType & operator+ (const NoConstant &, const Eigen::MatrixBase< RhsType > &rhs)
Adding an absent constant part with an existing constant part.
template<typename LhsType >
const LhsType & operator+ (const Eigen::MatrixBase< LhsType > &lhs, const NoConstant &)
Adding an existing constant part with an absent constant part.
auto operator+ (const NoConstant &, const NoConstant &)
Adding two absent constant parts.
template<typename MultType >
NoConstant operator* (const MultType &, const NoConstant &)
Overload for post-multiplying by NoConstant.
template<typename Tuple , size_t ... Indices>
auto tupleUnaryMinus (const Tuple &tuple, std::index_sequence< Indices... >)
Taking the opposite of each element i of the input tuple where the i's are the elements given by the sequence of index.
template<typename MultType , typename Tuple , size_t ... Indices>
auto tuplePremult (const MultType &m, const Tuple &tuple, std::index_sequence< Indices... >)
Premultiplication by m of each element i of the input tuple where the i's are the elements given by the sequence of index.
template<typename Object , typename Output , typename... Args>
void parseSourcesAndOutputs (graph::CallGraph *g, std::shared_ptr< graph::internal::Inputs > user, std::shared_ptr< Object > obj, Output output, Args &&... args)
Recursion over the sources and outputs.
template<typename Object1 , typename Object2 , typename... Args>
void parseSourcesAndOutputs (graph::CallGraph *g, std::shared_ptr< graph::internal::Inputs > user, std::shared_ptr< Object1 > obj1, std::shared_ptr< Object2 > obj2, Args &&... args)
Recursion over the sources and outputs.
template<typename Object >
void parseSourcesAndOutputs (graph::CallGraph *g, std::shared_ptr< graph::internal::Inputs > user, std::shared_ptr< Object > obj)
Recursion over the sources and outputs.
Typedef Documentation
AddConstantsRetType
template<typename LhsType , typename RhsType > using tvm::utils::internal::AddConstantsRetType = typedef std::remove_const_t<std::remove_reference_t<decltype(std::declval<LhsType>() + std::declval<RhsType>())> >
Result type for the addition of two constant parts, existing or not.
IdentityType
using tvm::utils::internal::IdentityType = typedef decltype(Eigen::MatrixXd::Identity())
Type of Eigen::MatrixXd::Identity()
map
template<typename KeyWithId , typename Value , typename Allocator = std::allocator< std::pair<const KeyWithId, Value> >> using tvm::utils::internal::map = typedef std::map<KeyWithId, Value, IdComparator<KeyWithId>, Allocator >
MinusIdentityType
using tvm::utils::internal::MinusIdentityType = typedef decltype(-Eigen::MatrixXd::Identity())
Type of -Eigen::MatrixXd::Identity()
MultIdentityType
using tvm::utils::internal::MultIdentityType = typedef decltype(2. * Eigen::MatrixXd::Identity())
Type of double*Eigen::MatrixXd::Identity()
RefSelector_t
template<typename Derived > using tvm::utils::internal::RefSelector_t = typedef typename RefSelector<Derived>::type
Enumeration Type Documentation
RHSType
enum tvm::utils::internal::RHSType strong
Describe the type of a right-hand-side argument.
Zero: the rhs is the zero vector
Double: the rhs is a vector with all elements equal to a given double
Vector: the rhs is a general vector
Enumerator
Zero
Double
Vector
Function Documentation
operator*()
template<typename MultType > NoConstant tvm::utils::internal::operator* (const MultType & , const NoConstant &) inline
Overload for post-multiplying by NoConstant.
In this case, we need to return NoConstant.
operator+() [1/3]
template<typename RhsType > const RhsType& tvm::utils::internal::operator+ (const NoConstant & , const Eigen::MatrixBase< RhsType > & rhs) inline
Adding an absent constant part with an existing constant part.
operator+() [2/3]
template<typename LhsType > const LhsType& tvm::utils::internal::operator+ (const Eigen::MatrixBase< LhsType > & lhs, const NoConstant &) inline
Adding an existing constant part with an absent constant part.
operator+() [3/3]
auto tvm::utils::internal::operator+ (const NoConstant & , const NoConstant &) inline
Adding two absent constant parts.
parseSourcesAndOutputs() [1/3]
template<typename Object , typename Output , typename... Args> void tvm::utils::internal::parseSourcesAndOutputs (graph::CallGraph * g, std::shared_ptr< graph::internal::Inputs > user, std::shared_ptr< Object > obj, Output output, Args &&... args) inline
Recursion over the sources and outputs.
Case where the next element to parse is an output.
Referenced by tvm::utils::generateUpdateGraph(), and parseSourcesAndOutputs().
parseSourcesAndOutputs() [2/3]
template<typename Object1 , typename Object2 , typename... Args> void tvm::utils::internal::parseSourcesAndOutputs (graph::CallGraph * g, std::shared_ptr< graph::internal::Inputs > user, std::shared_ptr< Object1 > obj1, std::shared_ptr< Object2 > obj2, Args &&... args) inline
Recursion over the sources and outputs.
Case where the next element to parse is a source.
References tvm::graph::CallGraph::add(), and parseSourcesAndOutputs().
parseSourcesAndOutputs() [3/3]
template<typename Object > void tvm::utils::internal::parseSourcesAndOutputs (graph::CallGraph * g, std::shared_ptr< graph::internal::Inputs > user, std::shared_ptr< Object > obj) inline
Recursion over the sources and outputs.
End of recursion.
References tvm::graph::CallGraph::add().
tuplePremult()
template<typename MultType , typename Tuple , size_t ... Indices> auto tvm::utils::internal::tuplePremult (const MultType & m, const Tuple & tuple, std::index_sequence< Indices... >)
Premultiplication by m of each element i of the input tuple where the i's are the elements given by the sequence of index.
Referenced by tvm::utils::operator*().
tupleUnaryMinus()
template<typename Tuple , size_t ... Indices> auto tvm::utils::internal::tupleUnaryMinus (const Tuple & tuple, std::index_sequence< Indices... >)
Taking the opposite of each element i of the input tuple where the i's are the elements given by the sequence of index.
Referenced by tvm::utils::operator-().