TVM: tvm::scheme::internal Namespace Reference
tvm::scheme::internal Namespace Reference
Classes
class ArgCount
Given a list of types, count how many of then havec a constructor accepting NoArg.
class ArgCount< T >
End of reccursion for ArgCount.
class AssignBase
Base class for the assignation.
class AssignBase< ADD >
class AssignBase< COPY >
class AssignBase< MAX >
class AssignBase< MIN >
class AssignBase< SUB >
class Assignment
A class whose role is to assign efficiently the matrix and vector(s) of a LinearConstraint to a part of matrix and vector(s) specified by a ResolutionScheme and a mapping of variables.
class AssignmentTarget
This class describes the matrix and vector(s) rows in which a given constraint needs to be copied, and the convention to be used for those matrix and vectors.
class CachedResult
A cache for holding temporary value in the evaluation of an assignment.
class CachedResult< MatrixType, true >
Specialization for when a cache is needed.
class CompiledAssignment
The main class.
class CompiledAssignment< MatrixType, A, W, M, ZERO >
Specialization for F=0.
class CompiledAssignment< MatrixType, COPY, W, M, ZERO >
Specialization for F=0 and A=COPY.
class CompiledAssignment< MatrixType, MAX, W, M, ZERO >
Specialization for F=0 and A=MAX.
class CompiledAssignment< MatrixType, MIN, W, M, ZERO >
Specialization for F=0 and A=MIN.
class CompiledAssignmentWrapper
This class wraps a CompiledAssignment so as to hide the template machinery.
class hasNoArgCtor
Traits-like class to detect if class T has a constructor accepting an instance of NoArg as argument.
class LevelAbilities
class MatrixMultBase
Base class for the multiplication by a matrix.
class MatrixMultBase< MatrixType, CUSTOM >
Partial specialization for CUSTOM.
class MatrixMultBase< MatrixType, GENERAL >
Partial specialization for GENERAL.
class MatrixMultBase< MatrixType, IDENTITY >
Partial specialization for IDENTITY.
class MatrixMultBase< MatrixType, INVERSE_DIAGONAL >
Partial specialization for INVERSE_DIAGONAL.
class NoArg
Dummy type for constructors with no arguments.
class ParseArg
A helper structure with a static get method to retrieve the N-th argument in a function call.
class ParseArg_
Helper structure to get the N-th argument in a function call.
class ParseNoArg_
Helper structure to get no argument in a function call.
class ProblemComputationData
Base class to be derived by each resolution scheme to hold all of the temporary memories and states related to the resolution of a problem.
class ResolutionSchemeBase
Base class for solving a ControlProblem.
class SchemeAbilities
A class to describe what type of constraint and solving requirements a resolution scheme can handle.
class SourceBase
Base class for managing the source.
class SourceBase< MatrixType, ZERO >
Partial specialization for ZERO.
class use_assign_cache
Traits for deciding whether or not to use a cache before the assign step.
class use_assign_cache< MatrixType, A, W, GENERAL, CONSTANT >
Specialization for GENERAL*CONSTANT.
class use_assign_cache< MatrixType, MAX, W, GENERAL, EXTERNAL >
class use_assign_cache< MatrixType, MIN, W, GENERAL, EXTERNAL >
Specialization for min/max with general matrix product.
class use_product_cache
Traits for deciding whether or not to use a cache for the product.
class use_product_cache< MatrixType, A, DIAGONAL, GENERAL, CONSTANT >
class use_product_cache< MatrixType, A, DIAGONAL, GENERAL, EXTERNAL >
Specialization for GENERAL product with diagonal weight.
class WeightMultBase
Base class for the multiplication by a scalar.
class WeightMultBase< DIAGONAL >
Specialization for DIAGONAL.
class WeightMultBase< MINUS >
Specialization for MINUS.
class WeightMultBase< NONE >
Specialization for NONE.
class WeightMultBase< SCALAR >
Specialization for SCALAR.
Typedefs
template<typename MatrixType >
using isVector = typename std::conditional< MatrixType::ColsAtCompileTime==1, std::true_type, std::false_type >::type
trait-like definition to detect if an Eigen expression MatrixType is describing a vector.
template<typename MatrixType >
using isMatrix = typename std::conditional< MatrixType::ColsAtCompileTime !=1, std::true_type, std::false_type >::type
Enumerations
enum TargetType {
TargetType::Linear,
TargetType::Quadratic
}
enum AssignType {
COPY,
ADD,
SUB,
MIN,
MAX
}
Specify in which way from is assigned to to.
enum WeightMult {
NONE,
MINUS,
SCALAR,
DIAGONAL
}
Specify whether from is to be multiplied by 1, -1 or a user specified scalar.
enum MatrixMult {
IDENTITY,
GENERAL,
INVERSE_DIAGONAL,
CUSTOM
}
Specify if from is to be multiplied a matrix, and if so, what is the type of the matrix.
enum Source {
EXTERNAL,
ZERO,
CONSTANT
}
The type of the source.
Functions
VectorConstRef retrieveSource (LinearConstraintPtr, const VectorConstRef &f)
Helper function for addVectorAssignment returning the Eigen::Ref to the source vector, where the argument is the vector in question.
VectorConstRef retrieveSource (LinearConstraintPtr s, const Assignment::RHSFunction &f)
Helper function for addVectorAssignment returning the Eigen::Ref to the source vector, where the argument is a method returning the vector.
VectorRef retrieveTarget (AssignmentTarget &, VectorRef v)
Helper function for addVectorAssignment and addConstantAssignment returning the Eigen::Ref to the target vector, where the argument is the vector in question.
VectorRef retrieveTarget (AssignmentTarget &t, Assignment::VectorFunction v)
Helper function for addVectorAssignment and addConstantAssignment returning the Eigen::Ref to the target vector, where the argument is a method returning the vector.
std::nullptr_t nullifyIfVecRef (const VectorConstRef &)
Helper function for addVectorAssignment returning nullptr.
std::nullptr_t nullifyIfVecRef (VectorRef)
Helper function for addVectorAssignment returning nullptr.
Assignment::RHSFunction nullifyIfVecRef (Assignment::RHSFunction f)
Helper function for addVectorAssignment returning its argument.
Assignment::VectorFunction nullifyIfVecRef (Assignment::VectorFunction v)
Helper function for addVectorAssignment returning its argument.
template<typename T >
std::true_type hasNoArgCtorDummy (const T &)
A dummy helper function to build hasNoArgCtor.
template<typename T >
decltype(hasNoArgCtorDummy(T(NoArg()))) hasNoArgCtor_ (int)
Helper function that exists only if T has a constructor accepting NoArg.
template<typename >
std::false_type hasNoArgCtor_ (...)
Overload that always exists.
template<typename Problem , typename Scheme >
ProblemComputationData * getComputationData (Problem &problem, const Scheme &resolutionScheme)
Get the computation data linked to a particular resolution scheme.
bool TVM_DLLAPI isBound (const ConstraintPtr &c)
We consider as bound a constraint with a single variable and a diagonal, invertible jacobian.
bool TVM_DLLAPI isBound (const ConstraintPtr &c, const hint::internal::Substitutions &subs)
Assert if a constraint is a bound in the presence of substitutions.
bool TVM_DLLAPI isBound (const ConstraintPtr &c, const std::vector< VariablePtr > &x, const std::vector< std::shared_ptr< function::BasicLinearFunction >> &xsub)
Assert if a constraint is a bound in the presence of substitutions.
bool TVM_DLLAPI canBeUsedAsBound (const ConstraintPtr &c, const hint::internal::Substitutions &subs, constraint::Type targetConvention)
Check if the constraint can be used as a bound for a given target convention.
bool TVM_DLLAPI canBeUsedAsBound (const ConstraintPtr &c, const std::vector< VariablePtr > &x, const std::vector< std::shared_ptr< function::BasicLinearFunction >> &xsub, constraint::Type targetConvention)
Version with separated susbtituted variables and substitution functions.
Typedef Documentation
isMatrix
template<typename MatrixType > using tvm::scheme::internal::isMatrix = typedef typename std::conditional<MatrixType::ColsAtCompileTime != 1, std::true_type, std::false_type>::type
isVector
template<typename MatrixType > using tvm::scheme::internal::isVector = typedef typename std::conditional<MatrixType::ColsAtCompileTime == 1, std::true_type, std::false_type>::type
trait-like definition to detect if an Eigen expression MatrixType is describing a vector.
Enumeration Type Documentation
AssignType
enum tvm::scheme::internal::AssignType
Specify in which way from is assigned to to.
Enumerator
COPY
to = from
ADD
to += from
SUB
to -= from
MIN
to = min(to, from)
MAX
to = max(to, from)
MatrixMult
enum tvm::scheme::internal::MatrixMult
Specify if from is to be multiplied a matrix, and if so, what is the type of the matrix.
Enumerator
IDENTITY
from
GENERAL
M*from (vector case) or from*M (matrix case) where M is a matrix.
INVERSE_DIAGONAL
inv(M) * from or from*inv(M) where M is diagonal
CUSTOM
use a custom multiplier
Source
enum tvm::scheme::internal::Source
The type of the source.
Note there are two considerations for explicitly introducing the CONSTANT case (versus requiring the user to give a Ref to a constant vector):
we can deal with it more efficiently
we take care automatically of any change of size of to or of the multiplier matrix.
Enumerator
EXTERNAL
source is an external vector or matrix (main use-case)
ZERO
source is zero
CONSTANT
source is a (non-zero) constant
TargetType
enum tvm::scheme::internal::TargetType strong
Enumerator
Linear
Quadratic
WeightMult
enum tvm::scheme::internal::WeightMult
Specify whether from is to be multiplied by 1, -1 or a user specified scalar.
Enumerator
NONE
from
MINUS
-from
SCALAR
s*from
DIAGONAL
diag(d) * from
Function Documentation
canBeUsedAsBound() [1/2]
bool TVM_DLLAPI tvm::scheme::internal::canBeUsedAsBound (const ConstraintPtr & c, const hint::internal::Substitutions & subs, constraint::Type targetConvention)
Check if the constraint can be used as a bound for a given target convention.
For example l <= x <= u is a bound, but it cannot be transformed into x >= lb.
canBeUsedAsBound() [2/2]
bool TVM_DLLAPI tvm::scheme::internal::canBeUsedAsBound (const ConstraintPtr & c, const std::vector< VariablePtr > & x, const std::vector< std::shared_ptr< function::BasicLinearFunction >> & xsub, constraint::Type targetConvention)
Version with separated susbtituted variables and substitution functions.
getComputationData()
template<typename Problem , typename Scheme > ProblemComputationData* tvm::scheme::internal::getComputationData (Problem & problem, const Scheme & resolutionScheme) inline
Get the computation data linked to a particular resolution scheme.
If this data does not exist, create it, using the resolution scheme as a factory
Parameters
The resolution scheme for which we want to get back the computation data. It needs to have a method createComputationData.
Referenced by tvm::scheme::abstract::ResolutionScheme< WeightedLeastSquares >::solve().
hasNoArgCtor_() [1/2]
template<typename T > decltype(hasNoArgCtorDummy(T(NoArg()))) tvm::scheme::internal::hasNoArgCtor_ (int)
Helper function that exists only if T has a constructor accepting NoArg.
We use hasNoArgCtorDummy as a mean to enable SFINAE.
hasNoArgCtor_() [2/2]
template<typename > std::false_type tvm::scheme::internal::hasNoArgCtor_ (...)
Overload that always exists.
It will only be chosen if the other overload does not exist.
hasNoArgCtorDummy()
template<typename T > std::true_type tvm::scheme::internal::hasNoArgCtorDummy (const T &)
A dummy helper function to build hasNoArgCtor.
isBound() [1/3]
bool TVM_DLLAPI tvm::scheme::internal::isBound (const ConstraintPtr & c)
We consider as bound a constraint with a single variable and a diagonal, invertible jacobian.
It would be possible to accept non-invertible sparse diagonal jacobians as well, in which case the zero elements of the diagonal would correspond to non-existing bounds, but this requires quite a lot of work for something that is unlikely to happen and could be expressed by changing the bound itself to +/- infinity.
isBound() [2/3]
bool TVM_DLLAPI tvm::scheme::internal::isBound (const ConstraintPtr & c, const hint::internal::Substitutions & subs)
Assert if a constraint is a bound in the presence of substitutions.
Parameters
c the constraint
subs the set of substitutions We have a bound if c is a bound and the variable is not substituted or it is by an expression with a single varaible and an invertible, diagonal jacobian.
isBound() [3/3]
bool TVM_DLLAPI tvm::scheme::internal::isBound (const ConstraintPtr & c, const std::vector< VariablePtr > & x, const std::vector< std::shared_ptr< function::BasicLinearFunction >> & xsub)
Assert if a constraint is a bound in the presence of substitutions.
Parameters
c the constraint
x the set of variables being substituted
xsub the set of substitution functions corresponding to those variables. We have a bound if c is a bound and the variable is not substituted or it is by an expression with a single varaible and an invertible, diagonal jacobian.
nullifyIfVecRef() [1/4]
std::nullptr_t tvm::scheme::internal::nullifyIfVecRef (const VectorConstRef &) inline
Helper function for addVectorAssignment returning nullptr.
Referenced by nullifyIfVecRef().
nullifyIfVecRef() [2/4]
std::nullptr_t tvm::scheme::internal::nullifyIfVecRef (VectorRef) inline
Helper function for addVectorAssignment returning nullptr.
nullifyIfVecRef() [3/4]
Assignment::RHSFunction tvm::scheme::internal::nullifyIfVecRef (Assignment::RHSFunction f) inline
Helper function for addVectorAssignment returning its argument.
nullifyIfVecRef() [4/4]
Assignment::VectorFunction tvm::scheme::internal::nullifyIfVecRef (Assignment::VectorFunction v) inline
Helper function for addVectorAssignment returning its argument.
References IDENTITY, NONE, nullifyIfVecRef(), tvm::constraint::OPPOSITE, retrieveSource(), retrieveTarget(), tvm::constraint::ZERO, and ZERO.
retrieveSource() [1/2]
VectorConstRef tvm::scheme::internal::retrieveSource (LinearConstraintPtr , const VectorConstRef & f) inline
Helper function for addVectorAssignment returning the Eigen::Ref to the source vector, where the argument is the vector in question.
Referenced by nullifyIfVecRef().
retrieveSource() [2/2]
VectorConstRef tvm::scheme::internal::retrieveSource (LinearConstraintPtr s, const Assignment::RHSFunction & f) inline
Helper function for addVectorAssignment returning the Eigen::Ref to the source vector, where the argument is a method returning the vector.
retrieveTarget() [1/2]
VectorRef tvm::scheme::internal::retrieveTarget (AssignmentTarget & , VectorRef v) inline
Helper function for addVectorAssignment and addConstantAssignment returning the Eigen::Ref to the target vector, where the argument is the vector in question.
Referenced by nullifyIfVecRef().
retrieveTarget() [2/2]
VectorRef tvm::scheme::internal::retrieveTarget (AssignmentTarget & t, Assignment::VectorFunction v) inline
Helper function for addVectorAssignment and addConstantAssignment returning the Eigen::Ref to the target vector, where the argument is a method returning the vector.