TVM: tvm::internal::FirstOrderProvider::slice_matrix Struct Reference
tvm::internal::FirstOrderProvider::slice_matrix Struct Reference
#include <tvm/internal/FirstOrderProvider.h>
Public Types
using Type = tvm::internal::ObjectWithProperties< MatrixRef, true >
using ConstType = MatrixConstRefWithProperties
Static Public Member Functions
static MatrixProperties slice (const MatrixProperties &p)
static Type get (MatrixWithProperties &M, const Range &r)
static ConstType get (const MatrixWithProperties &M, const Range &r)
Member Typedef Documentation
ConstType
using tvm::internal::FirstOrderProvider::slice_matrix::ConstType = MatrixConstRefWithProperties
Type
using tvm::internal::FirstOrderProvider::slice_matrix::Type = tvm::internal::ObjectWithProperties<MatrixRef, true>
Member Function Documentation
get() [1/2]
static Type tvm::internal::FirstOrderProvider::slice_matrix::get (MatrixWithProperties & M, const Range & r) inline static
References tvm::internal::ObjectWithProperties< MatrixType, refOnProperties >::properties().
get() [2/2]
static ConstType tvm::internal::FirstOrderProvider::slice_matrix::get (const MatrixWithProperties & M, const Range & r) inline static
slice()
static MatrixProperties tvm::internal::FirstOrderProvider::slice_matrix::slice (const MatrixProperties & p) inline static
References tvm::internal::MatrixProperties::isConstant(), tvm::internal::MatrixProperties::isZero(), and tvm::internal::MatrixProperties::ZERO.