TVM: tvm::internal::FirstOrderProvider Class Reference
tvm::internal::FirstOrderProvider Class Reference
Describes an entity that can provide a value and its jacobian.
#include <tvm/internal/FirstOrderProvider.h>
Classes
struct slice_linear
struct slice_matrix
Public Member Functions
virtual const Eigen::VectorXd & value () const
Return the value of this entity.
virtual MatrixConstRefWithProperties jacobian (const Variable &x) const
Return the jacobian matrix of this entity corresponding to the variable x.
bool linearIn (const Variable &x) const
Linearity w.r.t x.
const Space & imageSpace () const
int size () const
Return the image space size.
int rSize () const
Size of the output value (representation size of the image space).
int tSize () const
Size of the tangent space to the image space (or equivalently row size of the jacobian matrices).
const VariableVector & variables () const
Return the variables.
Public Member Functions inherited from tvm::graph::internal::AbstractNode
template<typename EnumT >
bool isUpdateEnabled (EnumT e) const
Check if a given update is enabled, be it at the class (static) or instance (dynamic) level).
virtual bool isUpdateStaticallyEnabled (int) const
Check if a given update is enabled at the class level (run-time).
virtual bool isUpdateCustomEnabled (int) const
Check if an update is enabled given a custom criterion.
virtual ~AbstractNode ()=default
void update (int i)
Call the function stored at index i.
Public Member Functions inherited from tvm::graph::internal::Inputs
virtual ~Inputs ()=default
template<typename T , typename EnumI , typename... Args>
void addInput (std::shared_ptr< T > source, EnumI i, Args... args)
Add outputs from a given Output object.
template<typename T , typename EnumI , typename... Args, typename std::enable_if< std::is_base_of< abstract::Outputs, T >::value, int >::type = 0>
void addInput (T &source, EnumI i, Args... args)
Add outputs from a given Output object.
template<typename T >
void removeInput (T *source)
Remove all outputs from a given Output object.
template<typename T , typename... Args>
void removeInput (T *source, Args... args)
Remove outputs from a given Output object.
template<typename T >
Iterator getInput (T *source)
Retrieve an input from a given Output object.
template<typename T >
Iterator getInput (const std::shared_ptr< T > &source)
Retrieve an input from a given Output object.
Public Member Functions inherited from tvm::graph::abstract::Outputs
virtual ~Outputs ()=default
template<typename EnumT >
bool isOutputEnabled (EnumT e) const
Check if a given output is enabled, be it at the class (static) or instance (dynamic) level).
bool isOutputEnabled (int i) const
Same as above, but taking int, for convenience.
virtual bool isOutputStaticallyEnabled (int) const
Check if a given output is enabled at the class level (run-time).
virtual bool isOutputCustomEnabled (int) const
Check if an output is enabled given a custom criterion.
Protected Member Functions
FirstOrderProvider (int m)
Constructor for a function/constraint with value in \(\mathbb{R}^m \).
FirstOrderProvider (Space image)
Constructor for a function/constraint with value in a specified space.
virtual void resizeCache ()
Resize all cache members corresponding to active outputs.
void resizeValueCache ()
Sub-methods of resizeCache resizing the value cache vector (if used).
void resizeJacobianCache ()
Sub-methods of resizeCache resizing the jacobian cache matrices (if used).
void addVariable (VariablePtr v, bool linear)
Add a variable.
void removeVariable (VariablePtr v)
Remove variable v.
void addVariable (const VariableVector &v, bool linear)
Add a variable vector.
virtual void addVariable_ (VariablePtr)
To be overridden by derived classes that need to react to the addition of a variable.
virtual void removeVariable_ (VariablePtr)
To be overridden by derived classes that need to react to the removal of a variable.
void splitJacobian (const MatrixConstRef &J, const std::vector< VariablePtr > &vars, bool keepProperties=false)
Split a jacobian matrix J into its components Ji corresponding to the provided variables.
void splitJacobian (const MatrixConstRef &J, const VariableVector &vars, bool keepProperties=false)
Overload for VariableVector operations.
void resize (int m)
Resize the function.
Protected Member Functions inherited from tvm::graph::abstract::Node< FirstOrderProvider >
void registerUpdates (EnumT u, void(U::*fn)(), Args... args)
Register updates.
void registerUpdates (EnumT u, void(U::*fn)())
Register a single update.
void addOutputDependency (EnumO o, EnumU u)
Add a dependency of an output to an update call.
void addOutputDependency (std::initializer_list< EnumO > os, EnumU u)
Add a dependency of multiple outputs to an update call.
void addInternalDependency (EnumU1 uDependent, EnumU2 u)
Add a dependency between two update calls.
void addInputDependency (EnumU u, std::shared_ptr< S > source, EnumO i, Args... args)
Add a dependency of an update function to multiple input signals from a source.
void addInputDependency (EnumU u, S &source, EnumO i, Args... args)
Add a dependency of an update function to multiple input signals from a source.
void addDirectDependency (EnumO o, std::shared_ptr< S > source, EnumI i)
Add a dependency of an output to an input signal and its source.
void addDirectDependency (EnumO o, S &source, EnumI i)
Add a dependency of an output to an input signal and its source.
Protected Attributes
Eigen::VectorXd value_
utils::internal::MapWithVariableAsKey< MatrixWithProperties, slice_matrix > jacobian_
Space imageSpace_
VariableVector variables_
utils::internal::MapWithVariableAsKey< bool, slice_linear > linear_
Protected Attributes inherited from tvm::graph::internal::AbstractNode
std::map< int, std::function< void(AbstractNode &)> > updates_
Map from a update id to corresponding dependency function.
std::map< int, std::vector< int > > outputDependencies_
Map from an output to the list of updates it depends on (expressed by the respective ids).
std::map< int, std::vector< int > > internalDependencies_
Map from an update to the list of updates it depends on (expressed by the respective ids).
std::map< int, input_dependency_t > inputDependencies_
std::map< int, std::pair< Outputs *, int > > directDependencies_
Map from an output to the input it directly uses, without requiring an update (expressed by the respective ids).
Protected Attributes inherited from tvm::graph::abstract::Outputs
bool is_node_ = false
Used to avoid a dynamic cast when working on Outputs that may be tvm::data::Node.
Additional Inherited Members
Public Types inherited from tvm::graph::internal::AbstractNode
enum Update_
Base Update enumeration.
using UpdateParent = AbstractNode
Meta-information regarding the class inheritance diagram.
using UpdateBase = AbstractNode
Meta-information used during inheritance to retrieve the base-class output size.
Public Types inherited from tvm::graph::internal::Inputs
using inputs_t = std::unordered_map< abstract::Outputs *, std::set< int > >
Type used to store the inputs.
using store_t = std::unordered_set< std::shared_ptr< abstract::Outputs > >
Type used to store the inputs data.
Public Types inherited from tvm::graph::abstract::Outputs
enum Output_
Base Output enumeration.
using OutputParent = Outputs
Meta-information regarding the class inheritance diagram.
using OutputBase = Outputs
Meta-information used during inheritance to retrieve the base-class output size.
Static Public Member Functions inherited from tvm::graph::internal::AbstractNode
static constexpr const char * UpdateName (Update_)
Return the name of a given update.
template<typename EnumT >
static constexpr bool UpdateStaticallyEnabled (EnumT)
Check if a given update is enabled (compile-time)
Static Public Member Functions inherited from tvm::graph::abstract::Outputs
static constexpr const char * OutputName (Output_)
Return the name of a given output.
template<typename EnumT >
static constexpr bool OutputStaticallyEnabled (EnumT)
Check if a given output is enabled at the class level (compile-time)
Static Public Attributes inherited from tvm::graph::internal::AbstractNode
static constexpr unsigned int UpdateSize = 0
Store the size of the Update enumeration.
static constexpr auto UpdateBaseName = "AbstractNode"
Meta-information holding the name of the class to which the Update enum belong.
Static Public Attributes inherited from tvm::graph::abstract::Outputs
static constexpr unsigned int OutputSize = 0
Store the size of the Output enumeration.
static constexpr auto OutputBaseName = "Outputs"
Meta-information holding the name of the class to which the Output enum belong.
Protected Types inherited from tvm::graph::internal::AbstractNode
using input_dependency_t = std::map< Outputs *, std::set< int > >
Map from an update to the list of inputs it depends on (expressed by the respective ids).
Detailed Description
Describes an entity that can provide a value and its jacobian.
Constructor & Destructor Documentation
FirstOrderProvider() [1/2]
tvm::internal::FirstOrderProvider::FirstOrderProvider (int m) protected
Constructor for a function/constraint with value in \(\mathbb{R}^m \).
Parameters
m the size of the function/constraint image space, i.e. the row size of the jacobians (or equivalently in this case the size of the output value).
FirstOrderProvider() [2/2]
tvm::internal::FirstOrderProvider::FirstOrderProvider (Space image) protected
Constructor for a function/constraint with value in a specified space.
Parameters
image Description of the image space
Member Function Documentation
addVariable() [1/2]
void tvm::internal::FirstOrderProvider::addVariable (VariablePtr v, bool linear) protected
Add a variable.
Cache is automatically updated.
Parameters
v The variable to add
linear Specify that the entity is depending linearly on the variable or not.
Referenced by tvm::function::BasicLinearFunction::BasicLinearFunction().
addVariable() [2/2]
void tvm::internal::FirstOrderProvider::addVariable (const VariableVector & v, bool linear) protected
Add a variable vector.
Convenience function similar to adding each elements of the vector individually with the same linear parameter
See also
addVariable(VariablePtr, bool)
addVariable_()
virtual void tvm::internal::FirstOrderProvider::addVariable_ (VariablePtr) protected virtual
To be overridden by derived classes that need to react to the addition of a variable.
Called at the end of addVariable();
Reimplemented in tvm::function::abstract::Function.
imageSpace()
const Space & tvm::internal::FirstOrderProvider::imageSpace () const inline
jacobian()
MatrixConstRefWithProperties tvm::internal::FirstOrderProvider::jacobian (const Variable & x) const inline virtual
Return the jacobian matrix of this entity corresponding to the variable x.
Reimplemented in tvm::constraint::internal::LinearizedTaskConstraint.
linearIn()
bool tvm::internal::FirstOrderProvider::linearIn (const Variable & x) const inline
Linearity w.r.t x.
removeVariable()
void tvm::internal::FirstOrderProvider::removeVariable (VariablePtr v) protected
Remove variable v.
Cache is automatically updated.
removeVariable_()
virtual void tvm::internal::FirstOrderProvider::removeVariable_ (VariablePtr) protected virtual
To be overridden by derived classes that need to react to the removal of a variable.
Called at the end of removeVariable();
Reimplemented in tvm::function::abstract::Function.
resize()
void tvm::internal::FirstOrderProvider::resize (int m) protected
Resize the function.
resizeCache()
virtual void tvm::internal::FirstOrderProvider::resizeCache () protected virtual
Resize all cache members corresponding to active outputs.
This can be overridden in case you do not need all of the default mechanism (typically if you will not use part of the cache). If you override to perform additional operations, do not forget to call this base version in the derived classes.
Reimplemented in tvm::constraint::abstract::Constraint, tvm::function::abstract::Function, and tvm::function::abstract::LinearFunction.
resizeJacobianCache()
void tvm::internal::FirstOrderProvider::resizeJacobianCache () protected
Sub-methods of resizeCache resizing the jacobian cache matrices (if used).
To be used by derived classes that need this level of granularity.
resizeValueCache()
void tvm::internal::FirstOrderProvider::resizeValueCache () protected
Sub-methods of resizeCache resizing the value cache vector (if used).
To be used by derived classes that need this level of granularity.
rSize()
int tvm::internal::FirstOrderProvider::rSize () const inline
Size of the output value (representation size of the image space).
size()
int tvm::internal::FirstOrderProvider::size () const inline
Return the image space size.
Referenced by tvm::function::BasicLinearFunction::BasicLinearFunction().
splitJacobian() [1/2]
void tvm::internal::FirstOrderProvider::splitJacobian (const MatrixConstRef & J, const std::vector< VariablePtr > & vars, bool keepProperties = false) protected
Split a jacobian matrix J into its components Ji corresponding to the provided variables.
Parameters
J The matrix to be split
vars The vector of variables giving the layout of J. It is the user's responsibility to ensure these variables are part of variables_ and that J has the correct size.
keepProperties If true, the properties associated with matrices Ji are kept, if not they are reset to default.
splitJacobian() [2/2]
void tvm::internal::FirstOrderProvider::splitJacobian (const MatrixConstRef & J, const VariableVector & vars, bool keepProperties = false) inline protected
Overload for VariableVector operations.
References tvm::VariableVector::variables().
tSize()
int tvm::internal::FirstOrderProvider::tSize () const inline
Size of the tangent space to the image space (or equivalently row size of the jacobian matrices).
value()
const Eigen::VectorXd & tvm::internal::FirstOrderProvider::value () const inline virtual
Return the value of this entity.
Reimplemented in tvm::robot::JointsSelector.
variables()
const VariableVector & tvm::internal::FirstOrderProvider::variables () const inline
Return the variables.
Referenced by tvm::function::BasicLinearFunction::BasicLinearFunction().
Member Data Documentation
imageSpace_
Space tvm::internal::FirstOrderProvider::imageSpace_ protected
jacobian_
utils::internal::MapWithVariableAsKey<MatrixWithProperties, slice_matrix> tvm::internal::FirstOrderProvider::jacobian_ protected
Referenced by tvm::function::BasicLinearFunction::BasicLinearFunction().
linear_
utils::internal::MapWithVariableAsKey<bool, slice_linear> tvm::internal::FirstOrderProvider::linear_ protected
value_
Eigen::VectorXd tvm::internal::FirstOrderProvider::value_ protected
variables_
VariableVector tvm::internal::FirstOrderProvider::variables_ protected