TVM: tvm::scheme::abstract::ResolutionScheme< Derived > Class Template Reference
tvm::scheme::abstract::ResolutionScheme< Derived > Class Template Reference
Resolution schemes may be defined only for a particular type of problems.
#include <tvm/scheme/abstract/ResolutionScheme.h>
Public Member Functions
template<typename Problem >
bool solve (Problem &problem) const
template<typename Problem >
std::unique_ptr< internal::ProblemComputationData > createComputationData (const Problem &problem) const
Derived & derived ()
Returns a reference to the derived object.
const Derived & derived () const
Returns a const reference to the derived object.
Public Member Functions inherited from tvm::scheme::internal::ResolutionSchemeBase
double big_number () const
void big_number (double big)
Public Member Functions inherited from tvm::internal::ObjWithId
ObjWithId (const ObjWithId &)=delete
ObjWithId & operator= (const ObjWithId &)=delete
int id () const
Protected Member Functions
ResolutionScheme (internal::SchemeAbilities abilities, double big=constant::big_number)
Protected Member Functions inherited from tvm::scheme::internal::ResolutionSchemeBase
ResolutionSchemeBase (SchemeAbilities abilities, double big=constant::big_number)
Constructor, meant only for derived classes.
Protected Member Functions inherited from tvm::internal::ObjWithId
ObjWithId ()
Additional Inherited Members
Protected Attributes inherited from tvm::scheme::internal::ResolutionSchemeBase
SchemeAbilities abilities_
double big_number_
A number to use for infinite bounds.
Detailed Description
template<typename Derived>
class tvm::scheme::abstract::ResolutionScheme< Derived >
Resolution schemes may be defined only for a particular type of problems.
We use CRTP for providing a common interface despite this, and performing some basic common operations.
The Derived class must provide:
one or several void solve_(ProblemType&, ComputationData&) methods (several if it handle differently several types of problems).
likewise, one or several createComputationData_(const ProblemType&) methods returning a std::unique_ptr<ComputationDataType> where ComputationDataType derives from ProblemComputationData.
For a given problem, the solve_ methods is guaranteed to receive the ComputationData instance created by createComputationData_ for the same problem.
Constructor & Destructor Documentation
ResolutionScheme()
template<typename Derived > tvm::scheme::abstract::ResolutionScheme< Derived >::ResolutionScheme (internal::SchemeAbilities abilities, double big = constant::big_number) inline protected
Referenced by tvm::scheme::abstract::ResolutionScheme< WeightedLeastSquares >::derived().
Member Function Documentation
createComputationData()
template<typename Derived > template<typename Problem > std::unique_ptr< internal::ProblemComputationData > tvm::scheme::abstract::ResolutionScheme< Derived >::createComputationData (const Problem & problem) const inline
derived() [1/2]
template<typename Derived> Derived& tvm::scheme::abstract::ResolutionScheme< Derived >::derived () inline
Returns a reference to the derived object.
Referenced by tvm::scheme::abstract::ResolutionScheme< WeightedLeastSquares >::createComputationData(), and tvm::scheme::abstract::ResolutionScheme< WeightedLeastSquares >::solve().
derived() [2/2]
template<typename Derived> const Derived& tvm::scheme::abstract::ResolutionScheme< Derived >::derived () const inline
Returns a const reference to the derived object.
solve()
template<typename Derived > template<typename Problem > bool tvm::scheme::abstract::ResolutionScheme< Derived >::solve (Problem & problem) const inline