TVM: tvm::Range Class Reference
tvm::Range Class Reference
A pair (start, dim) representing the integer range from start (included) to start+dim (excluded).
#include <tvm/Range.h>
Public Member Functions
Range ()
Range (int s, int d)
int end () const
First integer not in the range.
bool operator== (const Range &other) const
bool operator!= (const Range &other) const
bool contains (int i) const
Return true if i is contained in the range.
bool contains (const Range &other) const
Return true if other is contained in the range.
bool intersects (const Range &other) const
Return true if both range intersects.
Range relativeRange (const Range &other) const
Return the range of other within this Range.
Public Attributes
int start
int dim
Detailed Description
A pair (start, dim) representing the integer range from start (included) to start+dim (excluded).
Constructor & Destructor Documentation
Range() [1/2]
tvm::Range::Range () inline
Range() [2/2]
tvm::Range::Range (int s, int d) inline
Member Function Documentation
contains() [1/2]
bool tvm::Range::contains (int i) const inline
Return true if i is contained in the range.
Referenced by intersects().
contains() [2/2]
bool tvm::Range::contains (const Range & other) const inline
Return true if other is contained in the range.
Empty ranges are considered contained if their start is in the range.
References contains(), end(), and start.
Referenced by contains().
end()
int tvm::Range::end () const inline
First integer not in the range.
Referenced by contains().
intersects()
bool tvm::Range::intersects (const Range & other) const inline
Return true if both range intersects.
References contains(), and start.
operator!=()
bool tvm::Range::operator!= (const Range & other) const inline
References tvm::operator==().
operator==()
bool tvm::Range::operator== (const Range & other) const inline
References dim, and start.
relativeRange()
Range tvm::Range::relativeRange (const Range & other) const inline
Return the range of other within this Range.
e.g Range(3,8).relativeRange(5,2) returns Range(2,2)
References dim, and start.
Member Data Documentation
dim
int tvm::Range::dim
Referenced by operator==(), and relativeRange().
start
int tvm::Range::start
Referenced by contains(), intersects(), operator==(), and relativeRange().