TVM: tvm::VariableVector Class Reference
tvm::VariableVector Class Reference
A vector of variables, with some useful manipulation/analysis functions.
#include <tvm/VariableVector.h>
Public Member Functions
VariableVector ()
VariableVector (const std::vector< VariablePtr > &variables)
VariableVector (std::initializer_list< VariablePtr > variables)
bool add (VariablePtr v)
Add a variable to the vector.
void add (const std::vector< VariablePtr > &variables)
Same as add(VariablePtr), but for adding a vector of variables.
void add (const VariableVector &variables)
Same as add(VariablePtr), but for adding a vector of variables.
bool remove (const Variable &v)
Remove a variable from the vector.
int totalSize () const
Sum of the sizes of all the variables.
int numberOfVariables () const
Number of variables.
const VariablePtr operator[] (int i) const
Elementwise access.
const std::vector< VariablePtr > & variables () const
whole vector access
const Eigen::VectorXd & value () const
Get the concatenation of all variables' value, in the order of the variables as given by variables().
void value (const VectorConstRef &val)
Set the value of all variables from a concatenated vector.
void computeMapping () const
Compute the mapping for all variables in this vector.
std::map< const Variable *, Range > computeMappingMap () const
Compute the mapping for every variabe and return it.
bool contains (const Variable &v) const
Check if this vector contains variable v or not.
int indexOf (const Variable &v) const
Find the index of variable v in the vector.
int stamp () const
A timestamp, used internally to determine if a mapping needs to be recomputed or not.
std::vector< VariablePtr >::const_iterator begin () const
Iterator to the first variable.
std::vector< VariablePtr >::const_iterator end () const
Iterator past the last variable.
Detailed Description
A vector of variables, with some useful manipulation/analysis functions.
One of the main use of this class is to determine variable mapping, i.e. given a vector aggregating all variables, which section of this vector would correspond to a given variable. There is two approaches for that: either build a map with computeMappingMap or use the method Variable::getMappingIn. The latter uses a cache in Variable in a way that if one invoke Variable::getMappingIn on any variable contained in a VariableVector, the mapping of all other contained variables will be computed and cached. For repeatedly querying the mapping of those variable w.r.t the same VariableVector, this is the fastest option. However it will be slow if querying alternatively mapping w.r.t different VariableVector on the same variable or set of variables.
A given variable can only appear once in a vector. Variables appear in the order they were added, ignoring duplicates.
FIXME would it make sense to derive from std::vector<std::shared_ptr<Variable>> ?
Constructor & Destructor Documentation
VariableVector() [1/3]
tvm::VariableVector::VariableVector ()
VariableVector() [2/3]
tvm::VariableVector::VariableVector (const std::vector< VariablePtr > & variables)
VariableVector() [3/3]
tvm::VariableVector::VariableVector (std::initializer_list< VariablePtr > variables)
Member Function Documentation
add() [1/3]
bool tvm::VariableVector::add (VariablePtr v)
Add a variable to the vector.
Parameters
v the variable to be added
Returns
True if the variable was added, false otherwise
add() [2/3]
void tvm::VariableVector::add (const std::vector< VariablePtr > & variables)
Same as add(VariablePtr), but for adding a vector of variables.
add() [3/3]
void tvm::VariableVector::add (const VariableVector & variables)
Same as add(VariablePtr), but for adding a vector of variables.
begin()
std::vector< VariablePtr >::const_iterator tvm::VariableVector::begin () const inline
Iterator to the first variable.
This enable to use VariableVector directly in range-based for loops
computeMapping()
void tvm::VariableVector::computeMapping () const
Compute the mapping for all variables in this vector.
The result is stored in each variable and can be queried by Variable::getMappingIn.
computeMappingMap()
std::map<const Variable*, Range> tvm::VariableVector::computeMappingMap () const
Compute the mapping for every variabe and return it.
contains()
bool tvm::VariableVector::contains (const Variable & v) const
Check if this vector contains variable v or not.
Referenced by tvm::function::BasicLinearFunction::BasicLinearFunction().
end()
std::vector< VariablePtr >::const_iterator tvm::VariableVector::end () const inline
Iterator past the last variable.
This enable to use VariableVector directly in range-based for loops
indexOf()
int tvm::VariableVector::indexOf (const Variable & v) const
Find the index of variable v in the vector.
Returns -1 if v is not present.
numberOfVariables()
int tvm::VariableVector::numberOfVariables () const
Number of variables.
operator[]()
const VariablePtr tvm::VariableVector::operator[] (int i) const
Elementwise access.
remove()
bool tvm::VariableVector::remove (const Variable & v)
Remove a variable from the vector.
Parameters
v the variable to be removed
Returns
True if the variable was removed, false otherwise
stamp()
int tvm::VariableVector::stamp () const
A timestamp, used internally to determine if a mapping needs to be recomputed or not.
totalSize()
int tvm::VariableVector::totalSize () const
Sum of the sizes of all the variables.
value() [1/2]
const Eigen::VectorXd& tvm::VariableVector::value () const
Get the concatenation of all variables' value, in the order of the variables as given by variables().
value() [2/2]
void tvm::VariableVector::value (const VectorConstRef & val)
Set the value of all variables from a concatenated vector.
Parameters
val The concatenated value of all the variables, in the order of the variables as given by variables().
variables()
const std::vector<VariablePtr>& tvm::VariableVector::variables () const
whole vector access
Referenced by tvm::scheme::internal::ProblemComputationData::removeVariable(), and tvm::internal::FirstOrderProvider::splitJacobian().