TVM: tvm::task_dynamics::Clamped< TD, TDImpl >::Impl Class Reference
tvm::task_dynamics::Clamped< TD, TDImpl >::Impl Class Reference
#include <tvm/task_dynamics/Clamped.h>
Public Member Functions
template<typename... Args>
Impl (FunctionPtr f, constraint::Type t, const Eigen::VectorXd &rhs, const Bounds &min, const Bounds &max, Args &&... args)
void updateValue () override
~Impl () override=default
const Eigen::VectorXd & min () const
Access to \(b_{min} \).
Eigen::VectorXd & min ()
Access to \(b_{min} \).
const Eigen::VectorXd & max () const
Access to \(b_{max} \).
Eigen::VectorXd & max ()
Access to \(b_{max} \).
Constructor & Destructor Documentation
Impl()
template<class TD , class TDImpl > template<typename... Args> tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::Impl (FunctionPtr f, constraint::Type t, const Eigen::VectorXd & rhs, const Bounds & min, const Bounds & max, Args &&... args) inline
~Impl()
template<class TD , class TDImpl = typename TD::Impl> tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::~Impl () override default
Member Function Documentation
max() [1/2]
template<class TD , class TDImpl = typename TD::Impl> const Eigen::VectorXd& tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::max () const inline
Access to \(b_{max} \).
Referenced by tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::max().
max() [2/2]
template<class TD , class TDImpl = typename TD::Impl> Eigen::VectorXd& tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::max () inline
Access to \(b_{max} \).
Warning
It is your responsibility to give a valid \(b_{max} \) i.e.
correct size
\(b_{min} \leq 0 \leq b_{max}\)
References tvm::task_dynamics::Clamped< TD, TDImpl >::Clamped(), tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::max(), and tvm::task_dynamics::Clamped< TD, TDImpl >::~Clamped().
min() [1/2]
template<class TD , class TDImpl = typename TD::Impl> const Eigen::VectorXd& tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::min () const inline
Access to \(b_{min} \).
min() [2/2]
template<class TD , class TDImpl = typename TD::Impl> Eigen::VectorXd& tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::min () inline
Access to \(b_{min} \).
Warning
It is your responsibility to give a valid \(b_{min} \) i.e.
correct size
\(b_{min} \leq 0 \leq b_{max}\)
updateValue()
template<class TD , class TDImpl > void tvm::task_dynamics::Clamped< TD, TDImpl >::Impl::updateValue () inline override